#ifndef MERE_MESSAGE_LIB_GLOBAL_H
#define MERE_MESSAGE_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MERE_MESSAGE_LIB)
#  define MERE_MESSAGE_LIB_SPEC Q_DECL_EXPORT
#else
#  define MERE_MESSAGE_LIB_SPEC Q_DECL_IMPORT
#endif

#endif // MERE_MESSAGE_LIB_GLOBAL_H
